#ifndef _ATTRIBUTENAME_H_
#define _ATTRIBUTENAME_H_

#define ATTRIBUTE_TITLE			"Title"
#define ATTRIBUTE_WIDTH			"Width"
#define ATTRIBUTE_HEIGHT		"Height"
#define ATTRIBUTE_COLOR			"Color"
#define ATTRIBUTE_TYPE			"Type"
#define ATTRIBUTE_PATH			"Path"
#define ATTRIBUTE_SIZE			"Size"
#define ATTRIBUTE_X				"X"
#define ATTRIBUTE_Y				"Y"
#define ATTRIBUTE_STARTX		"StartX"
#define ATTRIBUTE_STARTY		"StartY"
#define ATTRIBUTE_ENDX			"EndX"
#define ATTRIBUTE_ENDY			"EndY"
#define ATTRIBUTE_POINTAX		"PointAX"
#define ATTRIBUTE_POINTAY		"PointAY"
#define ATTRIBUTE_POINTBX		"PointBX"
#define ATTRIBUTE_POINTBY		"PointBY"
#define ATTRIBUTE_POINTCX		"PointCX"
#define ATTRIBUTE_POINTCY		"PointCY"
#define ATTRIBUTE_RADIUS		"Radius"
#define ATTRIBUTE_RADIUSX		"RadiusX"
#define ATTRIBUTE_RADIUSY		"RadiusY"
#define ATTRIBUTE_WIDTH			"Width"
#define ATTRIBUTE_ISFILLED		"IsFilled"
#define ATTRIBUTE_STARTANGLE	"StartAngle"
#define ATTRIBUTE_ENDANGLE		"EndAngle"
#define ATTRIBUTE_ALPHA			"Alpha"
#define ATTRIBUTE_CONTENT		"Content"
#define ATTRIBUTE_BACKCOLOR		"BackColor"

#endif // !_ATTRIBUTENAME_H_
